demoproject/demo/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from demo.views import *

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('validate_username/', validate_username, name='validate_username'),
    path('validate_email/', validate_email, name='validate_email'),

    path('', catalog, name='catalog'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path(r'product/<pk>', product, name='product'),

    path('cart', cart, name='cart'),
    path('checkout', checkout, name='checkout'),
    path('orders', OrderListView.as_view(), name='orders'),
    path('delete_orders/<pk>', delete_order, name='delete_order'),

    path('to_cart/<pk>', to_cart, name='to_cart'),
    path('remove_from_cart/<pk>', remove_from_cart, name='remove_from_cart'),
]

demoproject/demoproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from demoproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo.urls')),
]
urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demoproject/demo/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django.utils.crypto import get_random_string


def get_name_file(instance, filename):
    return '/'.join([get_random_string(length=5) + '_' + filename])


# Create your models here.
class User(AbstractUser):
    name = models.CharField(max_length=254, verbose_name='Имя', blank=False)
    surname = models.CharField(max_length=254, verbose_name='Фамилия', blank=False)
    patronymic = models.CharField(max_length=254, verbose_name='Отчество', blank=True)
    username = models.CharField(max_length=254, verbose_name='Логин', unique=True, blank=False)
    email = models.CharField(max_length=254, verbose_name='Почта', unique=True, blank=False)
    password = models.CharField(max_length=254, verbose_name='Пароль', blank=False)
    role = models.CharField(max_length=254, verbose_name='Роль',
                            choices=(('admin', 'Администратор'), ('user', 'Пользователь')), default='user')

    USERNAME_FIELD = 'username'

    def full_name(self):
        # return self.name + ' ' + self.surname + ' ' + self.patronymic;
        return ' '.join([self.name, self.surname, self.patronymic])

    def __str__(self):
        return self.full_name()


class Product(models.Model):
    name = models.CharField(max_length=254, verbose_name='Имя', blank=False)
    date = models.DateField(verbose_name='Дата добавления', auto_now_add=True)
    photo_file = models.ImageField(max_length=254, upload_to=get_name_file, blank=True, null=True,
                                   validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    year = models.IntegerField(verbose_name='Год производства', blank=True)
    country = models.CharField(max_length=254, verbose_name='Страна производства', blank=True)
    price = models.DecimalField(verbose_name='Стоимость', blank=False, max_digits=10, decimal_places=2, default=0.00)
    count = models.IntegerField(verbose_name='Количество', blank=False, default=1)
    category = models.ForeignKey('Category', verbose_name='Категория', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('product', args=[str(self.id)])

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=254, verbose_name='Наименование', blank=False)

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS_CHOICES = [
        ('new', 'Новый'),
        ('confirmed', 'Подтвержденный'),
        ('canceled', 'Отмененный')
    ]
    date = models.DateField(verbose_name='Дата оформления', auto_now_add=True)
    status = models.CharField(max_length=254, verbose_name='Статус',
                              choices=STATUS_CHOICES, default='new')
    user = models.ForeignKey('User', verbose_name='Пользователь', on_delete=models.CASCADE)
    rejection_reason = models.TextField(verbose_name='Причина отказа', blank=True)
    products = models.ManyToManyField(Product, through='ProductInOrder', related_name='orders')

    def count_product(self):
        count = 0
        for item_order in self.productinorder_set.all():
            count += item_order.count
        return count

    def status_verbose(self):
        return dict(self.STATUS_CHOICES)[self.status]

    def __str__(self):
        return self.date.ctime() + ' | ' + self.user.full_name() + ' | ' + str(self.count_product())


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, verbose_name='Заказ', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE)
    count = models.IntegerField(verbose_name='Количество', blank=False, default=0)
    price = models.DecimalField(verbose_name='Стоимость', blank=False, max_digits=10, decimal_places=2, default=0.00)


class Cart(models.Model):
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    count = models.IntegerField(verbose_name='Количество', blank=False, default=0)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)

    def __int__(self):
        return self.product.name + ' _ ' + str(self.count)

demoproject/demo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from demo.models import User


def validate_password_len(password):
    if len(password) < 6:
        raise ValidationError('Длина пароля не может быть меньше 6 символов')


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин',
                               validators=[RegexValidator('^[a-zA-Z0-9-]+$',
                                                          message="Разрешение только латиница, цифра или тире")],
                               error_messages={
                                   'required': 'Обязательное поле',
                                   'unique': 'Данный логин занят'
                               })
    email = forms.EmailField(label='Адрес электронной почты',
                             error_messages={
                                 'invalid': 'Не правильный формат адреса',
                                 'unique': 'Данный адрес занят'
                             })
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput,
                               validators=[validate_password_len],
                               error_messages={
                                   'required': 'Обязательное поле',
                               })
    password2 = forms.CharField(label='Пароль(Повторно)',
                                widget=forms.PasswordInput,
                                error_messages={
                                    'required': 'Обязательное поле',
                                })
    rules = forms.BooleanField(required=True,
                               label='Согласие с правилами регистрации',
                               error_messages={
                                   'required': 'Обязательное поле'
                               })
    name = forms.CharField(label='Имя',
                           validators=[RegexValidator('^[а-яА-Я-]+$',
                                                      message="Разрешение только латиница, цифра или тире")],
                           error_messages={
                               'required': 'Обязательное поле'
                           })
    surname = forms.CharField(label='Фамилия',
                              validators=[RegexValidator('^[а-яА-Я-]+$',
                                                         message="Разрешение только латиница, цифра или тире")],
                              error_messages={
                                  'required': 'Обязательное поле'
                              })
    patronymic = forms.CharField(label='Отчество',
                                 validators=[RegexValidator('^[а-яА-Я-]+$',
                                                            message="Разрешение только латиница, цифра или тире")])

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password and password2 and password != password2:
            raise ValidationError({
                'password2': ValidationError('Введенние пароли не совпадают', code='password_mismatch')
            })

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password2', 'name', 'surname', 'patronymic', 'rules')


class OrderForm(forms.ModelForm):
    def clean(self):
        status = self.cleaned_data.get('status')
        rejection_reason = self.cleaned_data.get('rejection_reason')
        if self.instance.status != 'new':
            raise forms.ValidationError({'status': "Статус можно сменить только у новых заказов"})
        if status == 'canceled' and not rejection_reason:
            raise forms.ValidationError({'rejection_reason': "При отказе нужно указать статус"})

demoproject/demo/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView

from demo.forms import RegisterUserForm
from demo.models import User, Order, Product, Cart, ProductInOrder, Category


# Create your views here.
class RegisterView(CreateView):
    template_name = 'registration/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('login')


def validate_username(request):
    username = request.GET.get('username', None)
    response = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(response);


def validate_email(request):
    email = request.GET.get('email', None)
    response = {
        'is_taken': User.objects.filter(email__iexact=email).exists()
    }
    return JsonResponse(response);


def about(request):
    products = Product.objects.filter(count__gte=1).order_by('-date')[:5]
    return render(request, 'demo/about.html', context={
        'products': products
    })


def catalog(request):
    category = request.GET.get('category')

    if category:
        products = Product.objects.filter(count__gte=1, category=category)
    else:
        products = Product.objects.filter(count__gte=1)

    order_by = request.GET.get('order_by')
    if order_by:
        products = products.order_by(order_by)
    else:
        products = products.order_by('-date')

    return render(request, 'demo/catalog.html', context={
        'category': Category.objects.all(),
        'products': products
    })


def contact(request):
    return render(request, 'demo/contact.html')


def product(request, pk):
    return render(request, 'demo/product.html')


@login_required
def cart(request):
    cart_items = request.user.cart_set.all()
    return render(request, 'demo/cart.html', context={
        'cart_items': cart_items
    })


class OrderListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'demo/orders.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('-date')


@login_required
def delete_order(request, pk):
    order = Order.objects.filter(user=request.user, pk=pk, status='new')
    if order:
        order.delete()
    return redirect('orders')


@login_required
def checkout(request):
    password = request.GET.get('password', None)
    valid = request.user.check_password(password)
    if not valid:
        return JsonResponse({
            'error': 'Не верный пароль'
        })
    item_in_cart = request.user.cart_set.all()
    if not item_in_cart:
        return JsonResponse({
            'error': 'Корзина пуста'
        })
    order = Order.objects.create(user=request.user)
    for item in item_in_cart:
        ProductInOrder.objects.create(order=order, product=item.product, count=item.count,
                                      price=item.count * item.product.price)
        item_in_cart.delete()
        return JsonResponse({
            'message': 'Заказ оформлен'
        })


@login_required
def to_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    item_in_cart = Cart.objects.filter(user=request.user, product=product).first()
    if item_in_cart:
        if item_in_cart.count + 1 > item_in_cart.product.count:
            return JsonResponse({
                'error': 'Can\'t add more'
            })
        item_in_cart.count += 1
        item_in_cart.save()
        return JsonResponse({
            'count': item_in_cart.count
        })
    item_in_cart = Cart(user=request.user, product=product, count=1)
    item_in_cart.save()
    return JsonResponse({
        'count': item_in_cart.count
    })


@login_required
def remove_from_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    item_in_cart = Cart.objects.filter(user=request.user, product=product).first()
    if not item_in_cart:
        return JsonResponse({
            'error': 'Не найдено'
        })
    if item_in_cart.count - 1 == 0:
        item_in_cart.delete()
        return JsonResponse({
            'count': 'Позиция удалена'
        })
    item_in_cart.count -= 1
    item_in_cart.save()
    return JsonResponse({
        'count': item_in_cart.count
    })

demoproject/templates/demo/about.html
{% extends "base.html" %}
{% block content %}

    <h1>О нас</h1>

    <div id="carouselExampleCaptions" class="carousel slide" data-mb-ride="carousel">
        <div class="carousel-inner">
            {% for item in products %}
                <div class="carousel-item
                {% if  forloop.counter == 1 %}
                    active
                {% endif %}
                ">
                    <img src="{{ item.photo_file.url }}" class="rounded mx-auto d-block w-60" alt="...">
                    <div class="carousel-caption d-none d-md-block bg-light">
                         <h3 class="text-dark" >{{ item.name }}</h3>
                    </div>

                </div>

            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-target="#carouselExampleCaptions" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-target="#carouselExampleCaptions" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </button>
    </div>
{% endblock %}

demoproject/templates/demo/cart.html
{% extends "base.html" %}
{% block content %}
    <h1>Корзина</h1>

    {% if cart_items %}
        <ul>
            {% for item in cart_items %}
                <li>
                    {{ item.product.name }} - <span id="item_count">{{ item.count }}</span>
                    <button onclick="RemoveFromCart(this,{{ item.product.pk }})">-</button>
                    <button onclick="toCart(this,{{ item.product.pk }})">+</button>
                </li>
            {% endfor %}
        </ul>
        <div>
            <input type="password" value="" name="password" placeholder="Введите пароль">
            <button id="by_order">Сформировать заказ</button>
        </div>
    {% else %}
        <p>Корзина пуста</p>
    {% endif %}


    <script>
        document.querySelector('#by_order').addEventListener('click', async (event) => {
            const password = document.querySelector('input').value;
            const res = await fetch(`/checkout?password=${password}`).then(res => res.json());
            if (res.error) {
                const message = document.createElement('div');
                message.innerHTML = res.error;
                event.target.parentElement.prepend(message);
                setTimeout(() => message.remove(), 1000);
            } else {
                location.href = '/orders';
            }
        })

        toCart = async (target, pk) => {
            const res = await fetch(`/to_cart/${pk}`).then(res => res.json());
            if (res.count) {
                let count = +document.querySelector('#item_count').innerHTML;
                document.querySelector('#item_count').innerHTML = count + 1;
            }
        }
        RemoveFromCart = async (target, pk) => {
            const res = await fetch(`/remove_from_cart/${pk}`).then(res => res.json());
            if (res.count) {
                let count = +document.querySelector('#item_count').innerHTML;
                document.querySelector('#item_count').innerHTML = count - 1;
            }
        }
    </script>

{% endblock %}

demoproject/templates/demo/catalog.html
{% extends "base.html" %}
{% block content %}
    <h1>Каталог</h1>
    <p>
    <div>Фильтр по категориям:</div>
    {% if not request.GET.category %}
        Все
    {% else %}
        <a href="{% url 'catalog' %}?order_by={{ request.GET.order_by }}">Все</a>
    {% endif %}
    {% for item in category %}
        <a href="{% url 'catalog' %}?category={{ item.pk }}&?order_by={{ request.GET.order_by }}">{{ item.name }}</a>
    {% endfor %}
    </p>

    <p>
    <div>Сортировка: </div>

    {% if not request.GET.order_by %}
        Сбросить
    {% else %}
     <a href="{% url 'catalog' %}?category={{ request.GET.category }}">Сбросить</a>
    {% endif %}
    <a href="{% url 'catalog' %}?order_by=name&category={{ request.GET.category }}">Наименование</a>
    <a href="{% url 'catalog' %}?order_by=year&category={{ request.GET.category }}">Год производства</a>
    <a href="{% url 'catalog' %}?order_by=price&category={{ request.GET.category }}">Цена</a>
    </p>

    {% for item in products %}
        <div class="d-flex">
            <img src="{{ item.photo_file.url }}" alt="{{ item.photo_file }}" class="img-thumbnail" width="200">
            <div class="p-2">
                <h3><a href="{{ item.get_absolute_url }}">{{ item.name }}</a> {{ item.price }} p.</h3>
                <div>
                    Год производства: {{ item.year }} / Категория: {{ item.category }} / Остаток: {{ item.count }}
                </div>
                {% if user.is_authenticated %}
                    <a href="#" onclick="toCart(this,{{ item.pk }})">В корзину</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}

    <script>
        toCart = async (target, pk) => {
            const res = await fetch(`/to_cart/${pk}`).then(res => res.json());
            const message = document.createElement('div');
            if (res.count) {
                message.innerHTML = `Товар добавлен в корзину. Общее кол-во товаров в корзине: ${res.count}`;
            } else {
                message.innerHTML = 'Больше нельзя добавить';
            }
            target.parentElement.append(message);
            setTimeout(() => message.remove(), 1000);
        }
    </script>
{% endblock %}

demoproject/templates/demo/checkout.html
{% extends "base.html" %}
{% block content %}
    <h1>Оформление заказа</h1>
{% endblock %}

demoproject/templates/demo/contact.html
{% extends "base.html" %}
{% block content %}
    <h1>Контакты</h1>
{% endblock %}

demoproject/templates/demo/orders.html
{% extends "base.html" %}
{% block content %}
    <h1>Мои заказы</h1>
    {% if order_list %}
        <ol>
            {% for order in order_list %}
                <li>
                    {{ order.date }} ({{ order.status }})
                    {% if order.status == 'new' %}
                        <a href="{% url 'delete_order' order.pk %}">Удалить заказ</a>
                    {% endif %}
                    {% if order.productinorder_set.all %}
                        <ul>
                            {% for item in order.productinorder_set.all %}
                                <li>{{ item.product.name }} | Количество: {{ item.count }} |
                                    Стоимость: {{ item.price }} </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <p>У вас пока нет заказов</p>
    {% endif %}
{% endblock %}

demoproject/templates/demo/product.html
{% extends "base.html" %}
{% block content %}
    <h1>Страница товара</h1>
{% endblock %}